"""Export composites into the harness a practitioner already runs.

The point of composing in place is to keep comparability, and that includes the plumbing:
a composite that only runs inside nonius would be a new instrument by another route. So
composites are emitted in the shapes two widely used harnesses already accept.

Neither exporter grades anything. Each carries the composite's gold through as the
reference answer, and the harness's own exact-match scorer does the rest -- which is the
same scorer the singleton items were graded with, and therefore the same measurement.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from typing import Any

from nonius.canonical import canonical_json


def _rendering(record: Mapping[str, Any], language: str) -> str | None:
    rendering = record.get("rendering", {})
    if not isinstance(rendering, dict):
        return None
    value = rendering.get(language)
    return str(value) if value is not None else None


def lm_eval_dataset(
    composites: Sequence[Mapping[str, Any]], *, language: str = "python"
) -> str:
    """JSONL rows for an lm-evaluation-harness task.

    One row per composite: the prompt, the gold as a JSON string, and the provenance a
    result table needs -- component count, longest path, the components themselves, the
    strata and the spec version -- so a score can be traced back to what it was composed
    from. Depth and path depth are both carried because DEPTH-ALL-0002 requires they never
    be conflated.
    """
    rows: list[str] = []
    for record in composites:
        prompt = _rendering(record, language)
        if prompt is None:
            continue
        rows.append(
            canonical_json(
                {
                    "id": record["id"],
                    "depth": record["depth"],
                    "path_depth": record.get("path_depth", record["depth"]),
                    "components": record["components"],
                    "spec": record.get("spec", ""),
                    "strata": record.get("strata", []),
                    "prompt": prompt,
                    "answer": json.dumps(record["gold"], sort_keys=True),
                }
            )
        )
    return "\n".join(rows) + ("\n" if rows else "")


def lm_eval_task_yaml(
    *, task: str = "nonius_composites", dataset_path: str = "composites.jsonl"
) -> str:
    """A minimal lm-evaluation-harness task config for the dataset above.

    Hand-written rather than generated from a schema, because a wrong YAML here silently
    scores the wrong field, and a reader should be able to check every line of it.
    """
    return f"""\
# Generated by nonius. Composite items whose gold is a deterministic function of the
# component golds; see the `components` field of each row for what each is composed from.
task: {task}
dataset_path: json
dataset_kwargs:
  data_files: {dataset_path}
test_split: train
output_type: generate_until
doc_to_text: "{{{{prompt}}}}"
doc_to_target: "{{{{answer}}}}"
generation_kwargs:
  until: ["\\n\\n"]
  do_sample: false
  temperature: 0.0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
"""


def inspect_ai_dataset(
    composites: Sequence[Mapping[str, Any]], *, language: str = "python"
) -> str:
    """JSONL in Inspect AI's ``Sample`` shape: ``input``, ``target``, ``id``, ``metadata``."""
    rows: list[str] = []
    for record in composites:
        prompt = _rendering(record, language)
        if prompt is None:
            continue
        rows.append(
            canonical_json(
                {
                    "id": record["id"],
                    "input": prompt,
                    "target": json.dumps(record["gold"], sort_keys=True),
                    "metadata": {
                        "depth": record["depth"],
                        "path_depth": record.get("path_depth", record["depth"]),
                        "components": record["components"],
                        "strata": record.get("strata", []),
                        "spec": record.get("spec", ""),
                    },
                }
            )
        )
    return "\n".join(rows) + ("\n" if rows else "")


EXPORTERS = {
    "lm-eval": lm_eval_dataset,
    "inspect": inspect_ai_dataset,
}
