#!/usr/bin/env python3
"""Generate docs/spec/rulings.md from the shipped rulings.

The docs page is generated and diffed in CI, so the site cannot state a ruling the package
does not carry. Run it after any change under src/nonius/spec/rulings/.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from nonius.spec.registry import all_rulings, spec_version  # noqa: E402

OUT = ROOT / "docs" / "spec" / "rulings.md"

TOPICS = {
    "core": "Core",
    "depth": "Depth",
    "link": "Links",
    "emit": "Emission",
    "bound": "The bound",
    "audit": "The audit",
}


def render() -> str:
    rulings = all_rulings()
    # The page is rendered by iterating a fixed topic map, so a ruling in an unlisted
    # topic would be silently omitted while the header count above still counted it.
    stray = sorted({r.topic for r in rulings} - set(TOPICS))
    if stray:
        raise SystemExit(
            f"tools/render_rulings.py: rulings exist in unlisted topics {stray}; "
            f"add them to TOPICS or the page will under-report the spec"
        )
    lines = [
        "# The rulings",
        "",
        "<!-- GENERATED by tools/render_rulings.py. Do not edit; edit the TOML. -->",
        "",
        f"Composition spec **{spec_version()}**, {len(rulings)} rulings.",
        "",
        "A ruling is one decision the composer makes, written down and given an id that "
        "never changes meaning. A number published under a ruling id means the same thing "
        "forever, which is why rulings are superseded by new ids rather than edited.",
        "",
        "Check what your installation carries with `nonius spec list`.",
        "",
    ]
    for topic, heading in TOPICS.items():
        members = [r for r in rulings if r.topic == topic]
        if not members:
            continue
        lines += [f"## {heading}", ""]
        for r in members:
            flag = "" if r.status == "active" else f" (**{r.status}**)"
            lines += [f"### `{r.id}`: {r.title}{flag}", ""]
            lines += [r.statement.strip(), ""]
            if r.rationale.strip():
                lines += ["**Why.**", "", r.rationale.strip(), ""]
            if r.examples:
                cited = ", ".join(f"`{c}`" for c in r.examples)
                lines += [f"Calibration cases: {cited}", ""]
            if r.superseded_by:
                lines += [f"Superseded by `{r.superseded_by}`.", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
